"""Multimodal Fusion Layer - V8.3.

Combines:
- wearable physiology
- longitudinal changes
- clinical variables
- ultrasound features
- manually entered measurements

Preserves provenance: WHERE DID THIS INFORMATION COME FROM?

For every conclusion, system knows source.

Example PCOS research signal:
40% clinical variables
25% longitudinal physiology
20% ultrasound-derived features
15% metabolic information
Values only used if actually generated by implemented model.

Separates:
MODEL CONFIDENCE vs DATA QUALITY vs CLINICAL VALIDATION
"""
from __future__ import annotations

import time
from dataclasses import dataclass, field
from typing import Dict, List, Optional

from src.config import (
    PROVENANCE_MEASURED, PROVENANCE_PATIENT_REPORTED,
    PROVENANCE_CLINICALLY_ENTERED, PROVENANCE_IMAGE_DERIVED,
    PROVENANCE_MODEL_INFERRED, PROVENANCE_UNKNOWN
)
from src.data_models import DiseaseModuleResult, SharedPhysiologicalFeatures


PROVENANCE_LABELS = {
    PROVENANCE_MEASURED: "Directly measured by sensor",
    PROVENANCE_PATIENT_REPORTED: "Patient-reported",
    PROVENANCE_CLINICALLY_ENTERED: "Clinically entered",
    PROVENANCE_IMAGE_DERIVED: "Derived from medical image",
    PROVENANCE_MODEL_INFERRED: "Model-inferred from measurements",
    PROVENANCE_UNKNOWN: "Unknown provenance",
}

GROUP_ORDER = ["clinical", "wearable", "longitudinal", "metabolic", "ecg", "ultrasound", "adherence"]


@dataclass
class FusionFeature:
    key: str
    label: str
    value: Optional[float]
    group: str
    provenance: str = PROVENANCE_UNKNOWN
    quality: float = 0.0
    source: str = ""
    unit: str = ""

    def as_dict(self) -> dict:
        return {
            "key": self.key, "label": self.label, "value": self.value,
            "group": self.group, "provenance": self.provenance,
            "quality": self.quality, "source": self.source, "unit": self.unit,
        }


@dataclass
class FusionContext:
    built_at: float = field(default_factory=time.time)
    features: List[FusionFeature] = field(default_factory=list)

    def by_group(self, group: str) -> List[FusionFeature]:
        return [f for f in self.features if f.group == group]

    def get(self, key: str) -> Optional[FusionFeature]:
        for f in self.features:
            if f.key == key:
                return f
        return None

    def present_groups(self) -> List[str]:
        seen: List[str] = []
        for f in self.features:
            if f.value is not None and f.group not in seen:
                seen.append(f.group)
        return [g for g in GROUP_ORDER if g in seen]

    def missing_groups(self) -> List[str]:
        return [g for g in GROUP_ORDER if g not in self.present_groups()]

    def group_weights(self) -> Dict[str, float]:
        from collections import Counter
        expected: Dict[str, int] = {}
        present: Dict[str, int] = Counter()
        quality_sum: Dict[str, float] = Counter()
        for f in self.features:
            expected[f.group] = expected.get(f.group, 0) + 1
            if f.value is not None:
                present[f.group] += 1
                quality_sum[f.group] += f.quality
        weights: Dict[str, float] = {}
        for g in GROUP_ORDER:
            if g not in expected or present[g] == 0:
                weights[g] = 0.0
                continue
            coverage = present[g] / expected[g]
            avg_q = quality_sum[g] / present[g]
            weights[g] = round(coverage * avg_q, 3)
        return weights

    def overall_quality(self) -> float:
        vals = [f.quality for f in self.features if f.value is not None]
        return round(sum(vals) / len(vals), 3) if vals else 0.0

    def coverage(self) -> float:
        if not self.features:
            return 0.0
        present = sum(1 for f in self.features if f.value is not None)
        return round(present / len(self.features), 3)

    def provenance_summary(self) -> List[dict]:
        from collections import Counter
        c: Counter = Counter()
        for f in self.features:
            c[f.provenance] += 1
        return [{"provenance": k, "label": PROVENANCE_LABELS.get(k, k), "count": c[k]}
                for k in (PROVENANCE_MEASURED, PROVENANCE_PATIENT_REPORTED,
                          PROVENANCE_CLINICALLY_ENTERED, PROVENANCE_IMAGE_DERIVED,
                          PROVENANCE_MODEL_INFERRED, PROVENANCE_UNKNOWN) if c[k]]

    def summary_text(self) -> str:
        lines = [
            "MULTIMODAL FUSION CONTEXT V8.3",
            "=" * 46,
            f"Groups present: {', '.join(self.present_groups()) or 'none'}",
            f"Groups missing: {', '.join(self.missing_groups()) or 'none'}",
            f"Overall data quality: {self.overall_quality():.2f}",
            f"Coverage: {self.coverage():.0%}",
            "",
        ]
        for g in GROUP_ORDER:
            feats = self.by_group(g)
            if not feats:
                continue
            lines.append(f"[{g.upper()}]")
            for f in feats:
                val = "-" if f.value is None else (
                    f"{f.value:.2f} {f.unit}".strip() if isinstance(f.value, float)
                    else f"{f.value} {f.unit}".strip())
                lines.append(f"  {f.label}: {val}  ({f.provenance}, quality {f.quality:.2f})")
            lines.append("")
        lines.append("Provenance legend: " + "; ".join(
            f"{k}={PROVENANCE_LABELS[k]}" for k in
            (PROVENANCE_MEASURED, PROVENANCE_PATIENT_REPORTED, PROVENANCE_CLINICALLY_ENTERED,
             PROVENANCE_IMAGE_DERIVED, PROVENANCE_MODEL_INFERRED, PROVENANCE_UNKNOWN)))
        return "\n".join(lines)


@dataclass
class FusionResult:
    """Result of multimodal fusion across disease modules."""

    timestamp_s: float = field(default_factory=time.time)
    context: FusionContext = field(default_factory=FusionContext)
    module_results: Dict[str, DiseaseModuleResult] = field(default_factory=dict)
    overall_signals: List[Dict] = field(default_factory=list)
    confidence_breakdown: Dict[str, float] = field(default_factory=dict)
    data_quality: float = 0.0
    clinical_validation: str = "NOT ESTABLISHED"
    explanation: str = ""
    recommendations: List[str] = field(default_factory=list)

    def as_dict(self) -> dict:
        return {
            "timestamp_s": self.timestamp_s,
            "module_results": {k: v.as_dict() for k, v in self.module_results.items()},
            "overall_signals": self.overall_signals,
            "confidence_breakdown": self.confidence_breakdown,
            "data_quality": self.data_quality,
            "clinical_validation": self.clinical_validation,
            "explanation": self.explanation,
            "recommendations": self.recommendations,
            "fusion_context": {
                "overall_quality": self.context.overall_quality(),
                "coverage": self.context.coverage(),
                "present_groups": self.context.present_groups(),
                "missing_groups": self.context.missing_groups(),
                "group_weights": self.context.group_weights(),
            }
        }


class FusionEngine:
    """Builds FusionContext and combines disease module outputs."""

    def __init__(self):
        pass

    def add_clinical(self, ctx: FusionContext, profile=None, cycle=None, symptoms=None) -> None:
        p = profile
        if p is not None:
            for key, label, val in (
                    ("age", "Age (years)", getattr(p, "age_years", None)),
                    ("bmi", "BMI", getattr(p, "bmi", None)),
                    ("cycle_length", "Usual cycle length (days)", getattr(p, "usual_cycle_length_days", None)),
                    ("cycle_irregular", "Self-reported cycle irregularity",
                     (1.0 if getattr(p, "cycle_irregular", None) else 0.0 if getattr(p, "cycle_irregular", None) is False else None))):
                if val is not None:
                    ctx.features.append(FusionFeature(
                        key=key, label=label, value=float(val) if isinstance(val, (int, float)) else val,
                        group="clinical", provenance=PROVENANCE_PATIENT_REPORTED,
                        quality=0.7, source="UserProfile"))

    def add_wearable(self, ctx: FusionContext, shared: Optional[SharedPhysiologicalFeatures] = None,
                     quality: float = 0.0) -> None:
        if not shared:
            return
        for key, label, unit, val in (
                ("hr", "Heart rate", "bpm", shared.heart_rate),
                ("resting_hr", "Resting HR", "bpm", shared.resting_heart_rate),
                ("rmssd", "HRV RMSSD", "ms", shared.hrv_rmssd),
                ("skin_temp", "Skin temperature", "°C", shared.skin_temp_c),
                ("activity", "Activity", "%", shared.activity_level)):
            q = shared.sensor_quality.get(key, quality) if shared.sensor_quality else quality
            ctx.features.append(FusionFeature(
                key=key, label=label, value=float(val) if val is not None else None,
                group="wearable", provenance=PROVENANCE_MEASURED if val is not None else PROVENANCE_UNKNOWN,
                quality=q, source="wearable", unit=unit))

    def add_longitudinal(self, ctx: FusionContext, longitudinal_report=None) -> None:
        if not longitudinal_report:
            return
        for metric, ml in getattr(longitudinal_report, 'per_metric', {}).items():
            if hasattr(ml, 'z_latest'):
                ctx.features.append(FusionFeature(
                    key=f"{metric}_z", label=f"{metric} deviation (SD)",
                    value=float(ml.z_latest), group="longitudinal",
                    provenance=PROVENANCE_MODEL_INFERRED, quality=0.8,
                    source="longitudinal engine"))
                if hasattr(ml, 'persistence_points'):
                    ctx.features.append(FusionFeature(
                        key=f"{metric}_persist", label=f"{metric} persistence",
                        value=float(ml.persistence_points), group="longitudinal",
                        provenance=PROVENANCE_MODEL_INFERRED, quality=0.8,
                        source="longitudinal engine"))

    def add_metabolic(self, ctx: FusionContext, bp=None, glucose=None) -> None:
        if bp and bp.get("systolic"):
            ctx.features.append(FusionFeature(
                key="systolic_bp", label="Systolic BP", value=float(bp["systolic"]),
                group="metabolic", provenance=PROVENANCE_PATIENT_REPORTED,
                quality=0.7, source="manual BP", unit="mmHg"))
        if glucose and glucose.get("value") is not None:
            ctx.features.append(FusionFeature(
                key="glucose", label="Glucose", value=float(glucose["value"]),
                group="metabolic", provenance=PROVENANCE_PATIENT_REPORTED,
                quality=0.7, source="manual glucose", unit="mg/dL"))

    def add_ultrasound(self, ctx: FusionContext, us: Optional[Dict] = None) -> None:
        if not us:
            return
        src = us.get("source") or PROVENANCE_UNKNOWN
        prov = PROVENANCE_CLINICALLY_ENTERED if src in (PROVENANCE_CLINICALLY_ENTERED, "clinical") else PROVENANCE_IMAGE_DERIVED
        for key, alt, label, unit in (
                ("us_cyst_size_mm", "cyst_size_mm", "Largest cyst (mm)", "mm"),
                ("us_volume_cc", "volume_cc", "Ovarian volume (cc)", "cc")):
            v = us.get(key, us.get(alt))
            ctx.features.append(FusionFeature(
                key=key, label=label, value=float(v) if v is not None else None,
                group="ultrasound", provenance=prov, quality=0.85,
                source="ultrasound exam", unit=unit))

    def build(self, profile=None, shared: Optional[SharedPhysiologicalFeatures] = None,
              longitudinal_report=None, bp=None, glucose=None, ultrasound=None,
              cycle=None, symptoms=None, wearable_quality: float = 0.0) -> FusionContext:
        ctx = FusionContext()
        self.add_clinical(ctx, profile, cycle, symptoms)
        self.add_wearable(ctx, shared, wearable_quality)
        self.add_longitudinal(ctx, longitudinal_report)
        self.add_metabolic(ctx, bp, glucose)
        self.add_ultrasound(ctx, ultrasound)
        return ctx

    def fuse(self, module_results: Dict[str, DiseaseModuleResult],
             context: FusionContext) -> FusionResult:
        """Combine disease module outputs into overall assessment."""

        overall_signals = []
        for name, result in module_results.items():
            if result.level in ("elevated", "high"):
                overall_signals.append({
                    "module": name,
                    "signal": result.signal,
                    "level": result.level,
                    "confidence": result.confidence,
                    "data_quality": result.data_quality,
                })

        # Confidence breakdown - separate concepts
        model_confidences = [r.confidence for r in module_results.values()]
        data_qualities = [r.data_quality for r in module_results.values()]

        confidence_breakdown = {
            "model_confidence": float(sum(model_confidences) / len(model_confidences)) if model_confidences else 0.0,
            "data_quality": float(sum(data_qualities) / len(data_qualities)) if data_qualities else 0.0,
            "clinical_validation": 0.0,  # NOT ESTABLISHED for all
            "fusion_coverage": context.coverage(),
            "fusion_quality": context.overall_quality(),
        }

        # Overall explanation
        if overall_signals:
            primary = max(overall_signals, key=lambda x: x["confidence"])
            explanation = (
                f"Multimodal fusion detected {len(overall_signals)} research signals. "
                f"Primary: {primary['module']} {primary['signal']} ({primary['level']}). "
                f"Data quality: {confidence_breakdown['data_quality']:.2f}, "
                f"Model confidence: {confidence_breakdown['model_confidence']:.2f}, "
                f"Clinical validation: NOT ESTABLISHED. "
                f"These are research signals, not diagnoses."
            )
        else:
            explanation = (
                f"No elevated research signals. All modules report low/moderate levels. "
                f"Data quality: {confidence_breakdown['data_quality']:.2f}. "
                f"Continue longitudinal monitoring."
            )

        recommendations = []
        if confidence_breakdown["data_quality"] < 0.5:
            recommendations.append("Improve sensor contact and data quality for more reliable signals.")
        if overall_signals:
            recommendations.append("Discuss relevant findings with qualified healthcare professional if symptomatic.")
            # Module-specific
            for sig in overall_signals:
                if sig["module"] == "sleep":
                    recommendations.append("Consider sleep hygiene review and consistent sleep-wake schedule.")
                if sig["module"] == "cardiometabolic":
                    recommendations.append("Consider lifestyle factors: activity, nutrition, and clinical metabolic screening if indicated.")
                if sig["module"] == "autonomic":
                    recommendations.append("Consider stress management and recovery: sleep, activity, relaxation.")
                if sig["module"] == "pcos":
                    recommendations.append("If menstrual irregularity or related symptoms present, discuss with clinician for PCOS evaluation using Rotterdam criteria.")
        else:
            recommendations.append("Maintain current monitoring. No action required based on current signals.")

        return FusionResult(
            context=context,
            module_results=module_results,
            overall_signals=overall_signals,
            confidence_breakdown=confidence_breakdown,
            data_quality=context.overall_quality(),
            clinical_validation="NOT ESTABLISHED",
            explanation=explanation,
            recommendations=list(dict.fromkeys(recommendations))  # dedup preserve order
        )
