#!/usr/bin/env python3
"""Demo: watch a wearable model upgrade itself while it is being worn.

Run from the project root::

    python3 scripts/demo_self_learning.py
    python3 scripts/demo_self_learning.py --days 10 --seed 3

Everything here is SIMULATED (``src.utils.wear_simulator``). The point of the demo is
to show the *mechanism* - which tiers unlock at which wearing time, what the model
absorbs, what it refuses to absorb, and what it refuses to claim - on a stream where
the truth is known. It is not evidence about any real person, and the script says so
at the end.

The output is deliberately plain text so it can be pasted into a log or a report.
"""
from __future__ import annotations

import argparse
import dataclasses
import sys
import tempfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src.core.adaptive_learning import AdaptiveConfig, AdaptiveWearableModel  # noqa: E402
from src.utils.wear_simulator import SyntheticWearer, WearEpisode, WearerProfile  # noqa: E402

SIMULATED_NOTE = (
    "SIMULATED stream - generated by src/utils/wear_simulator.py. "
    "No real person was measured for this demo."
)


def hr(value: float) -> str:
    return f"{value:5.1f} h"


def run_ladder(days: float, seed: int, directory: Path) -> AdaptiveWearableModel:
    print("=" * 78)
    print("1. UPGRADE TIMELINE - the model earns capability from wearing time")
    print("=" * 78)
    profile = WearerProfile(patient_id="demo-ladder", hr_offset=9.0, rmssd_offset=-11.0,
                            temp_offset=0.5, seed=seed)
    wearer = SyntheticWearer(dataclasses.replace(profile))
    model = AdaptiveWearableModel("demo-ladder", path=directory / "ladder.json")
    start = wearer.start_ts
    for row in wearer.stream(days):
        for event in model.observe(row):
            hours = (event.at - start) / 3600.0
            print(f"  {hours:6.1f} h worn  {event.kind.upper():9s}  {event.detail}")
    status = model.status()
    print()
    print(f"  final tier          : {status['tier']} (model v{status['model_version']})")
    print(f"  wearing time        : {status['worn_hours']:.1f} h over {status['days_covered']} day(s)")
    print(f"  learned HR norm     : {status['metrics']['hr_bpm']['median']} bpm "
          f"(population prior: 72.0 bpm, this wearer's truth: 79.0 bpm)")
    print(f"  time-of-day hours   : {status['metrics']['hr_bpm']['hours_covered']}")
    print(f"  confidence          : {status['confidence']} "
          f"({status['confidence_note']})")
    return model


def run_capability_comparison(days: float, seed: int, directory: Path) -> None:
    print()
    print("=" * 78)
    print("2. WHAT THE UPGRADE BUYS - persistent shift vs short excursion")
    print("=" * 78)
    shift = WearEpisode(start_h=120.0, duration_h=72.0,
                        deltas={"hr_bpm": 9.0, "rmssd_ms": -8.0})
    spike = WearEpisode(start_h=132.0, duration_h=3.0, transient=True,
                        deltas={"hr_bpm": 14.0, "rmssd_ms": -12.0})
    profile = WearerProfile(patient_id="demo", hr_offset=6.0, rmssd_offset=-6.0, seed=seed)
    marks = (120.0, 132.0, 144.0, 168.0, 186.0)

    def play(cfg: AdaptiveConfig, episodes, name: str):
        wearer = SyntheticWearer(dataclasses.replace(profile), episodes=episodes)
        model = AdaptiveWearableModel(name, config=cfg, path=directory / f"{name}.json")
        trace: dict = {}
        start = wearer.start_ts
        for row in wearer.stream(days):
            model.observe(row)
            wall = (row.timestamp_s - start) / 3600.0
            for mark in marks:
                if mark not in trace and wall >= mark:
                    trace[mark] = model.evaluate("hr_bpm", 85.0)["z"]
        return model, trace

    adaptive, adaptive_trace = play(AdaptiveConfig(), [shift], "demo-adaptive")
    static, static_trace = play(AdaptiveConfig(adaptive_min_worn_s=1e9), [shift], "demo-static")
    transient, _ = play(AdaptiveConfig(), [spike], "demo-spike")

    def line(trace: dict) -> str:
        cells = []
        for mark in marks:
            z = trace.get(mark)
            cells.append(f"{z:>11.2f}" if z is not None else f"{'n/a':>11s}")
        return "".join(cells)

    print("  A 3-day shift of +9 bpm starts at hour 120.")
    print("  Deviation z-score of the shifted level, measured while the shift is running:")
    print("      marker    " + "".join(f"{m:>10.0f} h" for m in marks))
    print("      adaptive  " + line(adaptive_trace))
    print("      circadian " + line(static_trace))
    print()
    print(f"  adaptive model   : tier {adaptive.tier}, "
          f"{len([e for e in adaptive.events if e.kind == 'drift'])} absorbed drift event(s)")
    print(f"  circadian model  : tier {static.tier}, "
          f"{len([e for e in static.events if e.kind == 'drift'])} absorbed drift event(s)")
    print(f"  3 h excursion    : tier {transient.tier}, "
          f"{len([e for e in transient.events if e.kind == 'drift'])} absorbed drift event(s), "
          f"norm moved {transient.metrics['hr_bpm'].absorbed_total:+.2f} bpm")
    print("  -> a shift that persists long enough becomes the new normal;")
    print("     a short excursion is left as an event and never copied into the baseline.")


def run_supervised_head(days: float, seed: int, directory: Path) -> None:
    print()
    print("=" * 78)
    print("3. SUPERVISED HEAD - only activates if it beats a base-rate predictor")
    print("=" * 78)

    def play(labels_follow_physiology: bool, name: str, seed: int):
        import random as _random

        hours = (6.0, 8.0, 10.0, 12.0, 14.0, 17.0, 19.0, 21.0)
        rng = _random.Random(seed * 31 + 7)
        episodes = []
        for day in range(int(days)):
            base = 24.0 * day
            abnormal_hours = set(rng.sample(hours, 4))
            for hour in hours:
                if labels_follow_physiology:
                    abnormal = hour in abnormal_hours
                    deltas = {"hr_bpm": 11.0, "rmssd_ms": -9.0} if abnormal else {}
                    symptom = abnormal
                else:
                    deltas = {}
                    symptom = rng.random() < 0.5
                episodes.append(WearEpisode(start_h=base + hour, duration_h=0.6, deltas=deltas,
                                            label=f"{name}-{day}-{hour}", symptom=symptom,
                                            label_delay_h=0.3))
        wearer = SyntheticWearer(WearerProfile(patient_id=name, seed=seed),
                                 wear_start_hour=None, wear_end_hour=None, episodes=episodes)
        model = AdaptiveWearableModel(name, path=directory / f"{name}.json")
        taken = 0
        for row in wearer.stream(days):
            model.observe(row)
            labels = wearer.labels()
            while taken < len(labels):
                ts, target, text = labels[taken]
                taken += 1
                model.record_label(text, target=target, at=ts)
        return model

    for description, follows in (("labels follow physiology", True),
                                 ("labels carry no signal", False)):
        model = play(follows, f"head-{'signal' if follows else 'noise'}", seed)
        head = model.status()["head"]
        print(f"  {description:26s} -> {head['status'].upper()}")
        print(f"      labelled {head['n_train']}, unseen {head['n_prospective']}, "
              f"wins {head['prospective_wins']}")
        if head["prospective_logloss"] is not None:
            print(f"      log-loss {head['prospective_logloss']:.3f} "
                  f"vs base rate {head['baseline_logloss']:.3f}")
        print(f"      {head['reason']}")
        print()


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--days", type=float, default=8.0, help="simulated days (default 8)")
    parser.add_argument("--seed", type=int, default=7, help="simulation seed")
    parser.add_argument("--keep", type=str, default=None,
                        help="directory for the learned state (default: a temp dir)")
    args = parser.parse_args(argv)

    print(SIMULATED_NOTE)
    print()
    if args.keep:
        directory = Path(args.keep)
        directory.mkdir(parents=True, exist_ok=True)
    else:
        directory = Path(tempfile.mkdtemp(prefix="endo-twin-learning-"))
    print(f"learned state written to: {directory}")

    run_ladder(args.days, args.seed, directory)
    run_capability_comparison(args.days, args.seed, directory)
    run_supervised_head(args.days, args.seed, directory)

    print("=" * 78)
    print("WHAT THIS DOES AND DOES NOT SHOW")
    print("=" * 78)
    print("  shows : the ladder promotes in order on wearing time and coverage; a persistent")
    print("          shift is absorbed while a short excursion is not; the supervised head")
    print("          refuses to activate when its labels carry no signal.")
    print("  does not show: any clinical validity, any diagnostic performance, or anything at")
    print("          all about a real person. Streams are synthetic, labels are synthetic, and")
    print("          nothing here has been reviewed by a clinician.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
